# # # # # # # # # # # # #
#      Zero Blog        #
# # # # # # # # # # # # #

# Basic
name:               "Zero"

author:
  github:           latelan
  email:            abelxiyou@qq.com

copyright:
  year:             2017
  name:             latelan

# Google-analytics
google-analytics:
  id:               "UA-98478757-1"

# Disqus
disqus:
  id:               

# URL
url:                "http://zero.latelan.com" # the base hostname & protocol for your site
#url:               "http://192.168.56.102:4001" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Shanghai
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/latelan"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
    #  - jekyll-seo-tag
  - jekyll-paginate
    #  - jekyll-admin

exclude:            [vendor]
