permalink: /:year/:month/:day/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

markdown: kramdown
highlighter: pygments

title : latelan's Blog
author :
  name : latelan
  email : coolboy1353@163.com
  github : latelan


production_url : http://latelan.github.io

nav:
  - text: 分类
    url : /categories.html
  - text: 标签
    url : /tags.html
  - text: 存档
    url : /archive.html
  - text: 链接
    url : /link.html
  - text: 关于
    url : /about.html

JB :
  version : 0.3.0

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
